language: go

go:
  - 1.4

install:
  - make get-deps
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make check
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

branches:
  only:
    - ng
