language: go

before_install:
 - sudo apt-get update -q
 - sudo apt-get install libvips15 curl

go:
  - tip

install:
  - make get-deps

script:
  - make check
  - make install

after_success:
  - source ./.travis/after_success
